apiVersion: 1

datasources:
  # Loki datasource for log aggregation
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    uid: loki
    isDefault: true
    jsonData:
      # Maximum number of lines to show in log viewer
      maxLines: 1000


  # Prometheus datasource for metrics
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    uid: prometheus
    jsonData:
      httpMethod: GET
